# T5 config
model_name: "google-t5/t5-small"
dataset_name: "cleaned_data/cleaned_aslg_pc12.csv"

max_input_length:  128
max_target_length: 128

logging_steps: 10

learning_rate: 0.0001
num_epochs: 5
train_batch_size: 16
eval_batch_size:  16
seed: 42
patience: 3  # early stopping